import { useLiveQuery } from "dexie-react-hooks";
import { BookOpenText, Database, Info, Languages, Palette } from "lucide-react";
import { db } from "../db/database";
import { useTranslations } from "../hooks/useQuranData";
import { usePreferences } from "../providers/PreferencesProvider";
export default function SettingsPage() {
  const { preferences, setPreferences } = usePreferences(); const downloads = useLiveQuery(() => db.downloads.toArray(), [], []);
  const bn = useTranslations("bn").data || []; const en = useTranslations("en").data || [];
  const update = (key, value) => setPreferences((current) => ({ ...current, [key]: value }));
  return <div className="settings-page page-shell"><header className="page-intro"><p className="eyebrow">Your reading space</p><h1>Settings</h1><p>Comfort, meaning, offline access, and transparent sources.</p></header><div className="settings-list">
    <Section icon={BookOpenText} title="Reading"><Range label="Arabic size" value={preferences.arabicSize} min="26" max="56" onChange={(value) => update("arabicSize", value)}/><Range label="Arabic line height" value={preferences.arabicLineHeight} min="1.7" max="2.6" step=".05" onChange={(value) => update("arabicLineHeight", value)}/></Section>
    <Section icon={Languages} title="Meaning"><div className="segmented">{["bn","en","both"].map((mode) => <button key={mode} className={preferences.meaningMode === mode ? "active" : ""} onClick={() => update("meaningMode", mode)}>{mode === "bn" ? "বাংলা" : mode === "en" ? "English" : "Both"}</button>)}</div><Select label="Bangla translation" value={preferences.banglaResourceId} items={bn.filter((item) => item.classification === "translation")} onChange={(value) => update("banglaResourceId", value)}/><Select label="English translation" value={preferences.englishResourceId} items={en} onChange={(value) => update("englishResourceId", value)}/><label className="setting-toggle"><span><strong>Study mode</strong><small>Show Al-Mukhtasar as explanation, never as ordinary translation</small></span><input type="checkbox" checked={preferences.studyMode} onChange={(event) => update("studyMode", event.target.checked)}/></label></Section>
    <Section icon={Palette} title="Appearance"><div className="theme-options">{[["system","System"],["light","Light"],["dark","Dark"],["reading","Sepia"]].map(([value,label]) => <button key={value} className={preferences.theme === value ? "active" : ""} onClick={() => update("theme", value)}>{label}</button>)}</div></Section>
    <Section icon={Database} title="Offline"><Status label="Arabic Quran" value="Available offline"/><Status label="Bangla meaning" value={downloads.some((item) => item.translationId?.startsWith("bengali_")) ? "Downloaded chapters" : "Online"}/><Status label="English meaning" value={downloads.some((item) => item.translationId?.startsWith("english_")) ? "Downloaded chapters" : "Online"}/><p className="source-caption">Translations are cached by source, version snapshot, and Surah. Another translation is never substituted silently.</p></Section>
    <Section icon={Info} title="Data Sources & About"><Source title="Arabic Quran" detail="Tanzil Project · Uthmani Quran Text · Version 1.1" href="https://tanzil.net/"/><Source title="Bengali & English meanings" detail="QuranEnc · verified direct official resources" href="https://quranenc.com/"/><Source title="Word study" detail="Quranic Arabic Corpus 0.4 · awaiting official licensed download" href="https://corpus.quran.com/download/"/><p className="source-caption">Canonical Arabic and provider wording are never altered. No AI-generated Quran, meaning, footnote, or explanation is used.</p></Section>
  </div></div>;
}
function Section({icon:Icon,title,children}) { return <section className="settings-section"><div className="settings-title"><Icon/><h2>{title}</h2></div><div className="settings-content">{children}</div></section>; }
function Range({label,value,onChange,...props}) { return <label className="range-row"><span>{label}<small>{value}</small></span><input type="range" value={value} onChange={(event) => onChange(Number(event.target.value))} {...props}/></label>; }
function Select({label,value,items,onChange}) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
function Status({label,value}) { return <div className="status-row"><span>{label}</span><strong>{value}</strong></div>; }
function Source({title,detail,href}) { return <a className="source-row" href={href} target="_blank" rel="noreferrer"><strong>{title}</strong><span>{detail}</span></a>; }
