import { X } from "lucide-react";
import { usePreferences } from "../../providers/PreferencesProvider";

export function ReaderSettings({ open, onClose, resources = [] }) {
  const { preferences, setPreferences } = usePreferences();
  if (!open) return null;
  const update = (key, value) => setPreferences((current) => ({ ...current, [key]: value }));
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-3 sm:items-center" role="dialog" aria-modal="true" aria-label="Reader settings"><div className="w-full max-w-lg rounded-3xl bg-base-100 p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Reader settings</h2><button className="btn btn-circle btn-ghost" onClick={onClose} aria-label="Close reader settings"><X/></button></div><label className="mt-5 block">Arabic font size: {preferences.arabicSize}px<input className="range range-primary mt-2" type="range" min="24" max="54" value={preferences.arabicSize} onChange={(e) => update("arabicSize", Number(e.target.value))}/></label><label className="mt-5 block">Bangla font size: {preferences.banglaSize}px<input className="range range-primary mt-2" type="range" min="14" max="28" value={preferences.banglaSize} onChange={(e) => update("banglaSize", Number(e.target.value))}/></label><label className="mt-5 flex items-center justify-between">Show Bangla translation<input className="toggle toggle-primary" type="checkbox" checked={preferences.showTranslation} onChange={(e) => update("showTranslation", e.target.checked)}/></label><label className="mt-5 block">Theme<select className="select select-bordered mt-2 w-full" value={preferences.theme} onChange={(e) => update("theme", e.target.value)}><option value="light">Light</option><option value="dark">Dark</option><option value="reading">Reading / Sepia</option></select></label><p className="mt-5 text-sm text-base-content/60">Translation source: {preferences.translationName}</p>{resources.length > 1 && <label className="mt-2 block">Bengali translation<select className="select select-bordered mt-2 w-full" value={preferences.translationId || ""} onChange={(e) => { const selected = resources.find((item) => item.id === Number(e.target.value)); setPreferences((current) => ({...current, translationId:selected.id, translationName:selected.name || selected.authorName || "Official Bengali translation"})); }}>{resources.map((resource) => <option key={resource.id} value={resource.id}>{resource.name || resource.authorName}</option>)}</select></label>}</div></div>;
}

